// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntcyamehzzgqpfbnhmzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Y3lhbWVoenpncXBmYm5obXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTI3MTQsImV4cCI6MjA2NzA4ODcxNH0.J_KJNSk6lNoChFi5SOrZasV1m1ik61N34NI6YFrgfjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});